---
- name: Ensure OSSEC agent package is installed
  apt:
    name: ossec-hids-agent
    state: present

- name: Copy OSSEC configuration
  template:
    dest: /var/ossec/etc/
    src: ossec.conf

- stat:
    path: /var/ossec/etc/client.keys
  register: ossec_client_keys

- name: Check for pre-existing agent registration
  command: /var/ossec/bin/manage_agents -l
  register: list_agents
  changed_when: false

- name: Make sure authd is not already running on OSSEC server
  delegate_to: ossec_manager
  command: pkill ossec-authd
  ignore_errors: true
  changed_when: false
  run_once: true

- name: Start authd on OSSEC server
  delegate_to: ossec_manager
  shell: >
    /var/ossec/bin/ossec-authd
    -i {{ ansible_eth1.ipv4.address }} -p 1515 &
  async: 0
  poll: 0
  run_once: true

- name: Run agent auth (if agent is not already added)
  command: >
    /var/ossec/bin/agent-auth
    -m {{ hostvars.ossec_manager.ansible_eth1.ipv4.address }}
    -p 1515
    -A {{ inventory_hostname }}
  when: not ossec_client_keys.stat.exists

- name: Restart OSSEC (client)
  service:
    name: ossec
    state: restarted

- name: Kill authd on OSSEC server
  delegate_to: ossec_manager
  command: pkill ossec-authd
  ignore_errors: true
  changed_when: false
  run_once: true

- name: Restart OSSEC (server)
  delegate_to: ossec_manager
  service:
    name: ossec
    state: restarted
  run_once: true
