---
- name: Ensure OSSEC agent package is installed
  apt:
    name: ossec-hids-agent
    state: present

- name: Copy OSSEC configuration
  template:
    dest: /var/ossec/etc/
    src: ossec.conf

- stat:
    path: /var/ossec/etc/client.keys
  register: ossec_client_keys

- name: Check for pre-existing agent registration
  command: /var/ossec/bin/manage_agents -l
  register: list_agents
  changed_when: false

