---
- include: packages_common.yml

- include: manager_config.yml
  when: "'ossec_manager' in group_names"

- include: agent_config.yml
  when: "'ossec_manager' not in group_names"

- include: manager_registration.yml
  when: "'ossec_manager' in group_names"

- include: agent_registration.yml
  when: "'ossec_manager' not in group_names"

- include: manager_cleanup.yml
  when: "'ossec_manager' in group_names"


