---
- name: Ensure OSSEC manager package is installed.
  apt:
    name: ossec-hids
    state: present

- name: Check to see if agent already exists.
  command: /var/ossec/bin/list_agents -a
  register: list_agents

- name: Create authd SSL key if none exists.
  command: openssl genrsa -out /var/ossec/etc/sslmanager.key 4096
  args:
    creates: /var/ossec/etc/sslmanager.key

- name: Create authd SSL cert if none exists.
  command: openssl req -new -x509 -batch -subj "/CA=AU/ST=Some-State/locality=city/O=Internet Widgits Pty Ltd/commonName=mon/organizationUnitName=section/emailAddress=admin@localhost" -key /var/ossec/etc/sslmanager.key -out /var/ossec/etc/sslmanager.cert -days 1825
  args:
    creates: /var/ossec/etc/sslmanager.cert
