---
- name: Make sure authd is not already running on OSSEC server
  when: "'ossec_manager' in group_names"
  command: pkill ossec-authd
  ignore_errors: true
  changed_when: false
  run_once: true

- name: Start authd on OSSEC server
  delegate_to: "{{ groups.ossec_manager | first }}"
  shell: >
    /var/ossec/bin/ossec-authd
    -i {{ hostvars[inventory_hostname]['ansible_' + ossec_networking_interface]['ipv4']['address'] }}
    -p 1515 &
  async: 0
  poll: 0
  run_once: true

