---
- name: Add GPG key for OSSEC apt repo.
  apt_key:
    url: http://ossec.wazuh.com/repos/apt/conf/ossec-key.gpg.key

- name: Install apt repo for OSSEC.
  copy:
    src: ossec.list
    dest: /etc/apt/sources.list.d/
  register: ossec_add_repo

- name: Update apt repo if changed.
  apt:
    update_cache: true
  when: ossec_add_repo.changed
