---
- name: ensure OSSEC manager package is installed
  apt:
    name: ossec-hids
    state: present

- name: check to see if agent already exists
  shell: /var/ossec/bin/list_agents -a
  register: list_agents

- name: create authd SSL keys
  shell: openssl genrsa -out /var/ossec/etc/sslmanager.key 4096
  args:
    creates: /var/ossec/etc/sslmanager.key
  when: list_agents != "{{ agent_hostname }}-{{ agent_ip }} is available."

- name: create ssl cert
  shell: openssl req -new -x509 -batch -subj "/CA=AU/ST=Some-State/locality=city/O=Internet Widgits Pty Ltd/commonName=mon/organizationUnitName=section/emailAddress=admin@localhost" -key /var/ossec/etc/sslmanager.key -out /var/ossec/etc/sslmanager.cert -days 365
  args:
    creates: /var/ossec/etc/sslmanager.cert
  when: list_agents != "{{ agent_hostname }}-{{ agent_ip }} is available."

- name: start authd
  shell: "/var/ossec/bin/ossec-authd -i {{ agent_ip }} -p 1515 >/dev/null 2>&1 &"
  async: 0
  poll: 0
  when: list_agents.stdout != "{{ agent_hostname }}-{{ agent_ip }} is available."

- name: kill authd if it is running
  shell: "pkill ossec-authd || true"

- name: restart OSSEC
  service:
    name: ossec
    state: restarted
